// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// recursive_bayes_ball_cpp
bool recursive_bayes_ball_cpp(Rcpp::List parents, Rcpp::List children, int exposure_index, int outcome_index, Rcpp::IntegerVector blocked_nodes);
RcppExport SEXP _TFRegAct_recursive_bayes_ball_cpp(SEXP parentsSEXP, SEXP childrenSEXP, SEXP exposure_indexSEXP, SEXP outcome_indexSEXP, SEXP blocked_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type parents(parentsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< int >::type exposure_index(exposure_indexSEXP);
    Rcpp::traits::input_parameter< int >::type outcome_index(outcome_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type blocked_nodes(blocked_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(recursive_bayes_ball_cpp(parents, children, exposure_index, outcome_index, blocked_nodes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TFRegAct_recursive_bayes_ball_cpp", (DL_FUNC) &_TFRegAct_recursive_bayes_ball_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_TFRegAct(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
