# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recursive_bayes_ball_cpp <- function(parents, children, exposure_index, outcome_index, blocked_nodes) {
    .Call(`_TFRegAct_recursive_bayes_ball_cpp`, parents, children, exposure_index, outcome_index, blocked_nodes)
}
